# Generated by Django 6.0.6 on 2026-06-18 21:11
import random
from django.db import migrations

def poblar_libros_iniciales(apps, schema_editor):
    # Obtenemos el modelo 'Libro' a través del histórico de la app 'ORM'
    Libro = apps.get_model('ORM', 'Libro')
    
    libros_a_crear = []
    
    # 1. Añadir el libro obligatorio de Gabriel García Márquez
    libros_a_crear.append(
        Libro(
            titulo="Cien años de soledad",
            autor="Gabriel García Márquez",
            paginas=471,
            disponible=True
        )
    )
    
    # 2. Generar los 99 restantes con datos aleatorios
    autores_ficticios = ["Julio Cortázar", "Isabel Allende", "Jorge Luis Borges", "Mario Vargas Llosa"]
    titulos_ficticios = ["Las aventuras de Django", "El misterio del ORM", "Crónicas de un programador", "El bug invisible"]
    
    for i in range(1, 100):
        titulo_random = f"{random.choice(titulos_ficticios)} Vol. {i}"
        autor_random = random.choice(autores_ficticios)
        paginas_random = random.randint(150, 600)
        disponible_random = random.choice([True, False])
        
        libros_a_crear.append(
            Libro(
                titulo=titulo_random,
                autor=autor_random,
                paginas=paginas_random,
                disponible=disponible_random
            )
        )
        
    # Insertar los 100 registros en lote (eficiencia SQL)
    Libro.objects.bulk_create(libros_a_crear)

class Migration(migrations.Migration):

    dependencies = [
        # Django enlazará esto automáticamente con tu migración anterior (ej. '0001_initial')
        ('ORM', '0001_initial'), 
    ]

    operations = [
        # Ejecuta la función para poblar la tabla al hacer migrate
        migrations.RunPython(poblar_libros_iniciales),
    ]